# Deploy the pkgdown site (often a test version).

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Set Development Mode Env Var
        if: github.ref_name != 'main'
        run: |
          echo "Ref is '${{ github.ref_name }}', setting PKGDOWN_DEV_MODE=devel"
          echo "PKGDOWN_DEV_MODE=devel" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Generate examples menu
        shell: Rscript {0}
        run: |
          gsm.utils::add_pkgdown_examples(pkgdown_yml = "_pkgdown.yml")

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy PR preview ğŸ§ª
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          # Don't clean the whole branch, just the target folder
          clean: false
          branch: gh-pages
          folder: docs
          # Deploy to a subdirectory named after the PR number
          target-folder: pr/${{ github.event.number }}

      - name: PR site URL ğŸŒ
        if: github.event_name == 'pull_request'
        run: |
          echo "ğŸŒ URL: https://gilead-biostats.github.io/${{ github.event.repository.name }}/pr/${{ github.event.number }}/dev"

      - name: Comment with PR site URL ğŸŒ
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const prSiteURL = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr/${context.issue.number}/dev`
            const comment = `ğŸŒ PR pkdgown deployed: [${prSiteURL}](${prSiteURL})`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });

      - name: Deploy pkgdown ğŸ“ƒ
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
